[theme]
primaryColor="#f81721"
backgroundColor="#111214"
secondaryBackgroundColor="#20232b"

textColor="#ffffff"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"

[client]
showSidebarNavigation = false